import { describe, expect, it } from 'vitest';

import { readGovernancePublicAuditClientVerifierBundle } from '@/lib/governance-public-audit-verifiers';

describe('governance-public-audit verifier bundle parser', () => {
  it('parses client verifier bundle rows with trust metadata', () => {
    const bundle = readGovernancePublicAuditClientVerifierBundle([
      {
        bundle_version: 'public_audit_client_verifier_bundle_v1',
        bundle_hash: 'hash-1',
        bundle_payload: {
          generated_at: '2026-04-21T04:00:00.000Z',
          failover_policy: {
            policy_key: 'default',
            policy_name: 'Default mirror failover policy',
            min_healthy_mirrors: 2,
            max_mirror_latency_ms: 2500,
            max_failures_before_cooldown: 2,
            cooldown_minutes: 10,
            prefer_same_region: false,
            required_distinct_regions: 1,
            required_distinct_operators: 1,
            mirror_selection_strategy: 'health_latency_diversity',
            max_mirror_candidates: 8,
            min_independent_directory_signers: 2,
            require_policy_ratification: true,
            min_policy_ratification_approvals: 2,
          },
          failover_order: [
            {
              mirror_id: 'mirror-1',
              mirror_key: 'mirror_primary',
              mirror_label: 'Primary Mirror',
              region_code: 'US-WEST',
              operator_label: 'Levela Ops',
              health_status: 'healthy',
              last_check_latency_ms: 120,
              failover_rank: 1,
            },
          ],
          signed_directory: {
            directory_hash: 'directory-hash-1',
            signature: 'sig-1',
            signer_key: 'ops_signer',
          },
          signed_directory_trust: {
            directory_id: 'directory-1',
            batch_id: 'batch-1',
            directory_hash: 'directory-hash-1',
            published_at: '2026-04-21T04:10:00.000Z',
            required_independent_signers: 2,
            approval_count: 3,
            independent_approval_count: 2,
            community_approval_count: 1,
            reject_count: 0,
            trust_quorum_met: true,
          },
          federation_diversity: {
            batch_id: 'batch-1',
            required_distinct_regions: 2,
            required_distinct_operators: 2,
            selected_mirror_count: 3,
            healthy_mirror_count: 2,
            distinct_region_count: 2,
            distinct_operator_count: 2,
            largest_operator_mirror_count: 1,
            largest_operator_share_percent: 50,
            meets_region_diversity: true,
            meets_operator_diversity: true,
          },
          policy_ratification: {
            policy_key: 'default',
            policy_hash: 'policy-hash-1',
            require_policy_ratification: true,
            min_policy_ratification_approvals: 2,
            required_independent_signers: 2,
            approval_count: 3,
            independent_approval_count: 2,
            community_approval_count: 1,
            reject_count: 0,
            ratification_met: true,
            latest_ratified_at: '2026-04-21T04:12:00.000Z',
          },
        },
        healthy_mirror_count: 2,
        quorum_met: true,
      },
    ]);

    expect(bundle).toEqual({
      bundleVersion: 'public_audit_client_verifier_bundle_v1',
      bundleHash: 'hash-1',
      bundlePayload: {
        generated_at: '2026-04-21T04:00:00.000Z',
        failover_policy: {
          policy_key: 'default',
          policy_name: 'Default mirror failover policy',
          min_healthy_mirrors: 2,
          max_mirror_latency_ms: 2500,
          max_failures_before_cooldown: 2,
          cooldown_minutes: 10,
          prefer_same_region: false,
          required_distinct_regions: 1,
          required_distinct_operators: 1,
          mirror_selection_strategy: 'health_latency_diversity',
          max_mirror_candidates: 8,
          min_independent_directory_signers: 2,
          require_policy_ratification: true,
          min_policy_ratification_approvals: 2,
        },
        failover_order: [
          {
            mirror_id: 'mirror-1',
            mirror_key: 'mirror_primary',
            mirror_label: 'Primary Mirror',
            region_code: 'US-WEST',
            operator_label: 'Levela Ops',
            health_status: 'healthy',
            last_check_latency_ms: 120,
            failover_rank: 1,
          },
        ],
        signed_directory: {
          directory_hash: 'directory-hash-1',
          signature: 'sig-1',
          signer_key: 'ops_signer',
        },
        signed_directory_trust: {
          directory_id: 'directory-1',
          batch_id: 'batch-1',
          directory_hash: 'directory-hash-1',
          published_at: '2026-04-21T04:10:00.000Z',
          required_independent_signers: 2,
          approval_count: 3,
          independent_approval_count: 2,
          community_approval_count: 1,
          reject_count: 0,
          trust_quorum_met: true,
        },
        federation_diversity: {
          batch_id: 'batch-1',
          required_distinct_regions: 2,
          required_distinct_operators: 2,
          selected_mirror_count: 3,
          healthy_mirror_count: 2,
          distinct_region_count: 2,
          distinct_operator_count: 2,
          largest_operator_mirror_count: 1,
          largest_operator_share_percent: 50,
          meets_region_diversity: true,
          meets_operator_diversity: true,
        },
        policy_ratification: {
          policy_key: 'default',
          policy_hash: 'policy-hash-1',
          require_policy_ratification: true,
          min_policy_ratification_approvals: 2,
          required_independent_signers: 2,
          approval_count: 3,
          independent_approval_count: 2,
          community_approval_count: 1,
          reject_count: 0,
          ratification_met: true,
          latest_ratified_at: '2026-04-21T04:12:00.000Z',
        },
      },
      healthyMirrorCount: 2,
      quorumMet: true,
      failoverPolicy: {
        policyId: null,
        policyKey: 'default',
        policyName: 'Default mirror failover policy',
        isActive: true,
        minHealthyMirrors: 2,
        maxMirrorLatencyMs: 2500,
        maxFailuresBeforeCooldown: 2,
        cooldownMinutes: 10,
        preferSameRegion: false,
        requiredDistinctRegions: 1,
        requiredDistinctOperators: 1,
        mirrorSelectionStrategy: 'health_latency_diversity',
        maxMirrorCandidates: 8,
        minIndependentDirectorySigners: 2,
        requirePolicyRatification: true,
        minPolicyRatificationApprovals: 2,
        updatedAt: null,
      },
      failoverOrder: [
        {
          mirrorId: 'mirror-1',
          mirrorKey: 'mirror_primary',
          mirrorLabel: 'Primary Mirror',
          regionCode: 'US-WEST',
          operatorLabel: 'Levela Ops',
          healthStatus: 'healthy',
          lastCheckLatencyMs: 120,
          failoverRank: 1,
        },
      ],
      signedDirectoryHash: 'directory-hash-1',
      signedDirectorySignature: 'sig-1',
      signedDirectorySignerKey: 'ops_signer',
      signedDirectoryTrust: {
        directoryId: 'directory-1',
        batchId: 'batch-1',
        directoryHash: 'directory-hash-1',
        publishedAt: '2026-04-21T04:10:00.000Z',
        requiredIndependentSigners: 2,
        approvalCount: 3,
        independentApprovalCount: 2,
        communityApprovalCount: 1,
        rejectCount: 0,
        trustQuorumMet: true,
      },
      federationDiversity: {
        batchId: 'batch-1',
        requiredDistinctRegions: 2,
        requiredDistinctOperators: 2,
        selectedMirrorCount: 3,
        healthyMirrorCount: 2,
        distinctRegionCount: 2,
        distinctOperatorCount: 2,
        largestOperatorMirrorCount: 1,
        largestOperatorSharePercent: 50,
        meetsRegionDiversity: true,
        meetsOperatorDiversity: true,
      },
      policyRatification: {
        policyKey: 'default',
        policyHash: 'policy-hash-1',
        requirePolicyRatification: true,
        minPolicyRatificationApprovals: 2,
        requiredIndependentSigners: 2,
        approvalCount: 3,
        independentApprovalCount: 2,
        communityApprovalCount: 1,
        rejectCount: 0,
        ratificationMet: true,
        latestRatifiedAt: '2026-04-21T04:12:00.000Z',
      },
    });
  });
});
